services:
  glmserver:
    build:
      context: .
      dockerfile: Dockerfile.night
      # args:
      #   CUDA_IMAGE: "nvidia/cuda:13.0.1-devel-ubuntu24.04"
    image: hotwa/vllm:nightly
    container_name: glmserver
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - ./.env
    command:
      - "--model"
      - "TheHouseOfTheDude/GLM-4.7-Flash_AWQ"
      - "--revision"
      - "W4A16_GS32"
      - "--trust-remote-code"
      - "--served-model-name"
      - "glm-4.7-flash"
      - "--dtype"
      - "half"
      - "--attention-backend"
      - "FLASHINFER"
      - "--tensor-parallel-size"
      - "2"
      - "--max-model-len"
      - "16384"
      - "--max-num-seqs"
      - "1"
      - "--gpu-memory-utilization"
      - "0.95"
      - "--tool-call-parser"
      - "glm47"
      - "--reasoning-parser"
      - "glm45"
      - "--enable-auto-tool-choice"
      - "--distributed-executor-backend"
      - "mp"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"
      - "--enforce-eager"
    environment:
      # - VLLM_ENFORCE_EAGER=1
      # - VLLM_DISABLE_CUDAGRAPH=1
      - NVIDIA_VISIBLE_DEVICES=all
      - CUDA_VISIBLE_DEVICES=0,1
      - VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
      - HF_HUB_ENABLE_HF_TRANSFER=0
      - VLLM_MLA_DISABLE=1
      - VLLM_DISABLE_FLASH_ATTN=1
      - VLLM_USE_FLASH_ATTN=0
      - NCCL_P2P_LEVEL=NVL
      # - NCCL_DEBUG=INFO
      - NCCL_P2P_DISABLE=1
      - NCCL_SHM_DISABLE=0
      - NCCL_IB_DISABLE=1
      - PYTORCH_ALLOC_CONF=expandable_segments:True
    tty: true
    shm_size: "16gb"
    ulimits:
      memlock: -1
      stack: 67108864
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/ping >/dev/null"]
      interval: 5s
      timeout: 3s
      retries: 240
      start_period: 600s


  litellm-router:
    image: docker.litellm.ai/berriai/litellm:main-stable
    container_name: litellm-router
    ports:
      - "4000:4000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml:ro
    env_file:
      - ./.env.litellm
    environment:
      # 通过 Docker DNS 用容器名访问 vLLM
      - VLLM_API_BASE=http://glmserver:8000/v1
      # 禁用 streaming logging（解决 vLLM Anthropic 兼容格式问题）
      - LITELLM_DISABLE_STREAMING_LOGGING=true
      # 可选：如果 llama.cpp 的 api_base 带了 /v1，需要禁用自动 append
      # - LITELLM_ANTHROPIC_DISABLE_URL_SUFFIX=true
    command: ["--config", "/app/config.yaml", "--host", "0.0.0.0", "--port", "4000"]
    restart: unless-stopped
    depends_on:
      glmserver:
        condition: service_healthy

networks:
  llmnet:
    driver: bridge
